import React, { useEffect, useState } from "react";
import { CheckCircle2, Copy, Download, History, Instagram, LoaderCircle, Palette, RefreshCw, X } from "lucide-react";
import { DailyPostAssignment, DailyPostVariant } from "../types";
import { downloadDailyPostPng, uploadDailyPostImage } from "../services/dailyPostImage";

type DailyPostEvent = 'view' | 'customize' | 'copy_caption' | 'download_feed' | 'download_story' | 'mark_as_used' | 'request_alternative';
interface Props { post?: DailyPostAssignment | null; history?: DailyPostAssignment[]; compact?: boolean; readOnly?: boolean; onEvent?: (event: DailyPostEvent, format?: 'feed' | 'story' | 'carousel' | 'none', variant?: DailyPostVariant) => Promise<void>; }
const categoryLabels: Record<string, string> = { prevention: "Prevenção", aesthetics: "Estética", orthodontics: "Ortodontia", implants: "Implantes e próteses", pediatric: "Odontopediatria", periodontics: "Saúde gengival", urgent_care: "Dor e urgência" };
const formatLabels: Record<string, string> = { single_card: "Card", carousel: "Carrossel", qa: "Pergunta e resposta", myth_truth: "Mito ou verdade", checklist: "Checklist" };
const buttonClass = "inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-xs font-black text-slate-700 hover:bg-slate-50 disabled:opacity-40";

export const DailyPostCard: React.FC<Props> = ({ post, history = [], compact = false, readOnly = false, onEvent }) => {
  const [editing, setEditing] = useState(false); const [busy, setBusy] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const [variant, setVariant] = useState<DailyPostVariant | null>(post?.customizedVariant ?? null);
  useEffect(() => { setVariant(post?.customizedVariant ?? null); if (post && !readOnly) void onEvent?.("view"); }, [post?.id]);
  if (!post) return <article className="rounded-[2rem] border border-slate-100 bg-white p-7"><Instagram className="h-6 w-6 text-slate-300" /><h2 className="mt-4 text-xl font-black">Seu Post do Dia</h2><p className="mt-2 text-sm font-medium text-slate-500">A biblioteca ainda está sendo preparada para este perfil.</p></article>;
  const content = post.contentSnapshot;
  const active = variant ?? { title: content.title, caption: content.caption, ctaText: content.ctaText, imageUrl: content.defaultImageUrl, includeLogo: true, displayName: "", instagramHandle: "", paletteKey: content.paletteKey };
  const act = async (key: string, task: () => Promise<void>) => { setBusy(key); setNotice(null); try { await task(); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível concluir."); } finally { setBusy(null); } };
  const download = (format: "feed" | "story") => act(format, async () => { await downloadDailyPostPng(post, format, active); await onEvent?.(format === "feed" ? "download_feed" : "download_story", format); });
  return <div className="space-y-5">
    <article className={`overflow-hidden rounded-[2rem] border border-slate-100 bg-white shadow-sm ${compact ? "p-6" : "p-8"}`}>
      <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-widest text-blue-600">Preparado para você hoje</p><h2 className="mt-1 text-2xl font-black">Seu Post do Dia</h2></div><div className="flex gap-2"><span className="rounded-full bg-cyan-50 px-3 py-2 text-[10px] font-black uppercase text-cyan-700">{categoryLabels[content.category]}</span><span className="rounded-full bg-slate-100 px-3 py-2 text-[10px] font-black uppercase text-slate-600">{formatLabels[content.editorialFormat]}</span></div></div>
      <div className="mt-6 rounded-[1.75rem] p-7 text-white" style={{ background: `linear-gradient(145deg,#123B5D,${active.paletteKey})` }}><Instagram className="h-7 w-7" /><h3 className="mt-16 max-w-xl text-3xl font-black">{active.title}</h3><p className="mt-4 max-w-xl text-sm font-semibold leading-relaxed text-white/85">{content.shortText}</p><p className="mt-8 inline-flex rounded-xl bg-white/15 px-4 py-3 text-sm font-black">{active.ctaText}</p></div>
      <p className="mt-5 whitespace-pre-line text-sm font-medium leading-relaxed text-slate-600">{active.caption}</p>
      {!readOnly && <div className="mt-6 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">
        <button onClick={() => setEditing(true)} className={buttonClass}><Palette className="h-4 w-4" />Personalizar</button>
        <button onClick={() => void act("copy", async () => { await navigator.clipboard.writeText(`${active.caption}\n\n${active.ctaText}`); await onEvent?.("copy_caption"); setNotice("Legenda copiada."); })} className={buttonClass}><Copy className="h-4 w-4" />Copiar legenda</button>
        <button onClick={() => void download("feed")} className={buttonClass}><Download className="h-4 w-4" />Baixar Feed</button>
        <button onClick={() => void download("story")} className={buttonClass}><Download className="h-4 w-4" />Baixar Story</button>
        <button onClick={() => void act("used", async () => { await onEvent?.("mark_as_used"); setNotice("Conteúdo marcado como utilizado."); })} className={buttonClass}><CheckCircle2 className="h-4 w-4" />Marcar como utilizado</button>
        <button onClick={() => void act("alternative", async () => { await onEvent?.("request_alternative"); setNotice("Outra opção foi preparada."); })} className={buttonClass}><RefreshCw className="h-4 w-4" />Ver outra opção</button>
      </div>}
      {busy && <p className="mt-4 flex items-center gap-2 text-xs font-bold text-blue-700"><LoaderCircle className="h-4 w-4 animate-spin" />Processando...</p>}{notice && <p className="mt-4 rounded-xl bg-blue-50 p-3 text-sm font-bold text-blue-800">{notice}</p>}
    </article>
    <article className="rounded-[2rem] border border-slate-100 bg-white p-6"><div className="flex items-center gap-2"><History className="h-5 w-5 text-blue-600" /><h3 className="font-black">Histórico recente</h3></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{history.slice(0, 8).map((item) => <div key={item.id} className="rounded-xl bg-slate-50 p-3"><p className="text-sm font-black">{item.contentSnapshot.title}</p><p className="mt-1 text-[10px] font-bold uppercase text-slate-400">{item.assignmentDate} · {item.status}</p></div>)}</div></article>
    {editing && <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/60 p-4"><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-[2rem] bg-white p-7"><div className="flex justify-between"><div><p className="text-[10px] font-black uppercase text-blue-600">Cópia exclusiva deste profissional</p><h3 className="text-2xl font-black">Personalizar post</h3></div><button onClick={() => setEditing(false)}><X /></button></div><div className="mt-6 space-y-4"><input className="input" value={active.title} onChange={(event) => setVariant({ ...active, title: event.target.value })} placeholder="Título" /><textarea className="input" rows={6} value={active.caption} onChange={(event) => setVariant({ ...active, caption: event.target.value })} /><input className="input" value={active.ctaText} onChange={(event) => setVariant({ ...active, ctaText: event.target.value })} placeholder="CTA" /><input className="input" value={active.imageUrl} onChange={(event) => setVariant({ ...active, imageUrl: event.target.value })} placeholder="Imagem aprovada (URL https)" /><label className="block rounded-xl border border-dashed border-slate-300 p-4 text-sm font-bold text-slate-600">Enviar imagem própria (JPG, PNG ou WebP)<input type="file" accept="image/jpeg,image/png,image/webp" className="mt-2 block w-full text-xs" onChange={(event) => { const file = event.target.files?.[0]; if (file) void act("upload", async () => setVariant({ ...active, imageUrl: await uploadDailyPostImage(file, post) })); }} /></label><div className="grid gap-4 sm:grid-cols-2"><input className="input" value={active.displayName} onChange={(event) => setVariant({ ...active, displayName: event.target.value })} placeholder="Clínica ou profissional" /><input className="input" value={active.instagramHandle} onChange={(event) => setVariant({ ...active, instagramHandle: event.target.value })} placeholder="@instagram" /></div><label className="flex items-center gap-3 text-sm font-bold"><input type="color" value={active.paletteKey} onChange={(event) => setVariant({ ...active, paletteKey: event.target.value })} />Cor de destaque permitida</label></div><button onClick={() => void act("customize", async () => { await onEvent?.("customize", "none", active); setVariant(active); setEditing(false); setNotice("Personalização salva somente neste post."); })} className="mt-6 w-full rounded-xl bg-blue-600 py-4 text-xs font-black uppercase tracking-widest text-white">Salvar personalização</button></div></div>}
  </div>;
};
