import React, { useMemo, useState } from "react";
import { CalendarClock, CopyPlus, Edit3, Eye, LoaderCircle, Plus, Send } from "lucide-react";
import { DailyPost, DailyPostCategory, DailyPostEventRecord, DailyPostFormat, DailyPostStatus } from "../types";

export interface DailyPostManagerInput {
  postId?: string; templateId?: string; title: string; caption: string; cta: string; imageUrl?: string; status: DailyPostStatus;
  publishAtMs?: number | null; expiresAtMs?: number | null; hook: string; shortText: string; ctaText: string;
  ctaType: 'schedule' | 'contact' | 'learn' | 'save' | 'share'; hashtags: string[]; category: DailyPostCategory;
  communicationGoal: 'education' | 'problem_awareness' | 'authority' | 'conversion'; targetAudienceTags: string[]; specialtyTags: string[];
  editorialFormat: DailyPostFormat; feedLayoutKey: string; storyLayoutKey: string; paletteKey: string;
  imageStrategy: 'library' | 'professional_photo' | 'clinic_photo' | 'uploaded_by_professional' | 'illustration' | 'no_photo';
  defaultImageUrl: string; carouselSlides: Array<{ title: string; text: string }>; isEvergreen: boolean; priority: number;
  availableFromMs?: number | null; availableUntilMs?: number | null;
}
interface Props { posts: DailyPost[]; events?: DailyPostEventRecord[]; onSave: (input: DailyPostManagerInput) => Promise<unknown>; }
const toInputDate = (value?: number) => value ? new Date(value - new Date().getTimezoneOffset() * 60_000).toISOString().slice(0, 16) : "";
const categories: Array<[DailyPostCategory, string]> = [["prevention", "Prevenção"], ["aesthetics", "Estética"], ["orthodontics", "Ortodontia"], ["implants", "Implantes"], ["pediatric", "Odontopediatria"], ["periodontics", "Periodontia"], ["urgent_care", "Urgência"]];

export const DailyPostManager: React.FC<Props> = ({ posts, events = [], onSave }) => {
  const [selected, setSelected] = useState<DailyPost | null>(null); const [title, setTitle] = useState(""); const [hook, setHook] = useState(""); const [shortText, setShortText] = useState(""); const [caption, setCaption] = useState(""); const [cta, setCta] = useState(""); const [imageUrl, setImageUrl] = useState("");
  const [status, setStatus] = useState<DailyPostStatus>("draft"); const [category, setCategory] = useState<DailyPostCategory>("prevention"); const [format, setFormat] = useState<DailyPostFormat>("single_card"); const [goal, setGoal] = useState<DailyPostManagerInput["communicationGoal"]>("education"); const [priority, setPriority] = useState(50); const [palette, setPalette] = useState("#18AFA5"); const [publishAt, setPublishAt] = useState(""); const [expiresAt, setExpiresAt] = useState(""); const [filterStatus, setFilterStatus] = useState<DailyPostStatus | "all">("all"); const [filterCategory, setFilterCategory] = useState<DailyPostCategory | "all">("all"); const [filterFormat, setFilterFormat] = useState<DailyPostFormat | "all">("all"); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<string | null>(null);
  const reset = () => { setSelected(null); setTitle(""); setHook(""); setShortText(""); setCaption(""); setCta(""); setImageUrl(""); setStatus("draft"); setCategory("prevention"); setFormat("single_card"); setGoal("education"); setPriority(50); setPalette("#18AFA5"); setPublishAt(""); setExpiresAt(""); };
  const edit = (post: DailyPost, duplicate = false) => { setSelected(duplicate ? null : post); setTitle(duplicate ? `${post.title} — cópia` : post.title); setHook(post.hook ?? post.title); setShortText(post.shortText ?? post.caption.slice(0, 300)); setCaption(post.caption); setCta(post.cta); setImageUrl(post.imageUrl ?? ""); setStatus(duplicate ? "draft" : post.status); setCategory(post.category ?? "prevention"); setFormat(post.editorialFormat ?? "single_card"); setGoal(post.communicationGoal ?? "education"); setPriority(post.priority ?? 50); setPalette(post.paletteKey ?? "#18AFA5"); setPublishAt(toInputDate(post.publishAt)); setExpiresAt(toInputDate(post.expiresAt)); };
  const filtered = useMemo(() => posts.filter((post) => (filterStatus === "all" || post.status === filterStatus) && (filterCategory === "all" || post.category === filterCategory) && (filterFormat === "all" || post.editorialFormat === filterFormat)), [posts, filterStatus, filterCategory, filterFormat]);
  const save = async () => { setBusy(true); setNotice(null); try { const slides = format === "carousel" ? Array.from({ length: 4 }, (_, index) => ({ title: index === 0 ? hook : index === 3 ? cta : `Ponto ${index}`, text: index === 0 ? shortText : index === 3 ? "Convite para o próximo passo." : shortText })) : []; await onSave({ postId: selected?.id, templateId: selected?.id, title, hook: hook || title, shortText, caption, cta, ctaText: cta, ctaType: "contact", hashtags: ["#SaudeBucal", "#Odontologia", "#SorvySmile"], category, communicationGoal: goal, targetAudienceTags: ["adults", "families"], specialtyTags: ["general_dentistry"], editorialFormat: format, feedLayoutKey: `feed-${format}`, storyLayoutKey: `story-${format}`, paletteKey: palette, imageStrategy: imageUrl ? "library" : "no_photo", defaultImageUrl: imageUrl, imageUrl, carouselSlides: slides, status, isEvergreen: true, priority, publishAtMs: publishAt ? new Date(publishAt).getTime() : null, expiresAtMs: expiresAt ? new Date(expiresAt).getTime() : null, availableFromMs: publishAt ? new Date(publishAt).getTime() : null, availableUntilMs: expiresAt ? new Date(expiresAt).getTime() : null }); setNotice("Conteúdo salvo na biblioteca."); reset(); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível salvar."); } finally { setBusy(false); } };
  return <section className="grid gap-6 xl:grid-cols-[1fr_.9fr]">
    <div className="grid gap-3 sm:grid-cols-3 xl:col-span-2"><div className="rounded-2xl bg-blue-50 p-4"><p className="text-2xl font-black text-blue-700">{events.filter((event) => event.eventType === "view").length}</p><p className="text-[9px] font-black uppercase text-blue-500">Visualizações</p></div><div className="rounded-2xl bg-cyan-50 p-4"><p className="text-2xl font-black text-cyan-700">{events.filter((event) => event.eventType.startsWith("download")).length}</p><p className="text-[9px] font-black uppercase text-cyan-500">Downloads</p></div><div className="rounded-2xl bg-emerald-50 p-4"><p className="text-2xl font-black text-emerald-700">{events.filter((event) => event.eventType === "mark_as_used").length}</p><p className="text-[9px] font-black uppercase text-emerald-500">Utilizados</p></div></div>
    <article className="rounded-[2rem] border border-slate-100 bg-white p-7"><div className="flex justify-between"><div><p className="text-[10px] font-black uppercase tracking-widest text-blue-600">Biblioteca central</p><h2 className="mt-1 text-2xl font-black">{selected ? "Editar conteúdo" : "Novo conteúdo"}</h2></div>{selected && <button onClick={reset} className="rounded-xl bg-slate-100 p-3"><Plus className="h-4 w-4" /></button>}</div>
      <div className="mt-6 space-y-3"><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Título" className="input" /><input value={hook} onChange={(event) => setHook(event.target.value)} placeholder="Gancho" className="input" /><textarea value={shortText} onChange={(event) => setShortText(event.target.value)} rows={3} placeholder="Mensagem curta da arte" className="input" /><textarea value={caption} onChange={(event) => setCaption(event.target.value)} rows={5} placeholder="Legenda completa" className="input" /><input value={cta} onChange={(event) => setCta(event.target.value)} placeholder="CTA" className="input" /><input value={imageUrl} onChange={(event) => setImageUrl(event.target.value)} placeholder="Imagem aprovada (URL https, opcional)" className="input" />
      <div className="grid gap-3 sm:grid-cols-3"><select value={category} onChange={(event) => setCategory(event.target.value as DailyPostCategory)} className="input">{categories.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={format} onChange={(event) => setFormat(event.target.value as DailyPostFormat)} className="input"><option value="single_card">Card</option><option value="carousel">Carrossel</option><option value="qa">Pergunta e resposta</option><option value="myth_truth">Mito ou verdade</option><option value="checklist">Checklist</option></select><select value={goal} onChange={(event) => setGoal(event.target.value as DailyPostManagerInput["communicationGoal"])} className="input"><option value="education">Educação</option><option value="problem_awareness">Reconhecimento</option><option value="authority">Autoridade</option><option value="conversion">Conversão</option></select></div>
      <div className="grid gap-3 sm:grid-cols-3"><select value={status} onChange={(event) => setStatus(event.target.value as DailyPostStatus)} className="input"><option value="draft">Rascunho</option><option value="scheduled">Programado</option><option value="published">Publicado</option><option value="inactive">Inativo</option><option value="archived">Arquivado</option></select><input type="number" value={priority} onChange={(event) => setPriority(Number(event.target.value))} min="0" max="1000" className="input" aria-label="Prioridade" /><input type="color" value={palette} onChange={(event) => setPalette(event.target.value)} className="input h-12" aria-label="Cor" /></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-[9px] font-black uppercase text-slate-400">Disponível a partir de<input type="datetime-local" value={publishAt} onChange={(event) => setPublishAt(event.target.value)} className="input mt-1" /></label><label className="text-[9px] font-black uppercase text-slate-400">Disponível até<input type="datetime-local" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)} className="input mt-1" /></label></div></div>
      <div className="mt-5 rounded-[1.5rem] p-6 text-white" style={{ background: `linear-gradient(145deg,#123B5D,${palette})` }}><Eye className="h-5 w-5" /><h3 className="mt-10 text-2xl font-black">{title || "Prévia do conteúdo"}</h3><p className="mt-3 text-sm font-medium text-white/80">{shortText || "A mensagem curta aparecerá aqui."}</p></div>
      <button disabled={busy || title.trim().length < 3 || shortText.trim().length < 10 || caption.trim().length < 10 || cta.trim().length < 3 || (status === "scheduled" && !publishAt)} onClick={() => void save()} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 py-4 text-xs font-black uppercase tracking-widest text-white disabled:opacity-40">{busy ? <LoaderCircle className="h-5 w-5 animate-spin" /> : status === "scheduled" ? <CalendarClock className="h-5 w-5" /> : <Send className="h-5 w-5" />}Salvar conteúdo</button>{notice && <p className="mt-4 rounded-xl bg-blue-50 p-3 text-sm font-bold text-blue-800">{notice}</p>}</article>
    <article className="rounded-[2rem] border border-slate-100 bg-white p-7"><div className="flex items-end justify-between"><div><p className="text-[10px] font-black uppercase text-slate-400">Histórico e filtros</p><h2 className="text-2xl font-black">{posts.length} conteúdos</h2></div><p className="text-xs font-bold text-slate-400">{posts.filter((post) => post.status === "published").length} publicados</p></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><select value={filterStatus} onChange={(event) => setFilterStatus(event.target.value as DailyPostStatus | "all")} className="input"><option value="all">Todos os status</option><option value="draft">Rascunhos</option><option value="scheduled">Programados</option><option value="published">Publicados</option><option value="inactive">Inativos</option><option value="archived">Arquivados</option></select><select value={filterCategory} onChange={(event) => setFilterCategory(event.target.value as DailyPostCategory | "all")} className="input"><option value="all">Todas as categorias</option>{categories.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={filterFormat} onChange={(event) => setFilterFormat(event.target.value as DailyPostFormat | "all")} className="input"><option value="all">Todos os formatos</option><option value="single_card">Card</option><option value="carousel">Carrossel</option><option value="qa">Pergunta e resposta</option><option value="myth_truth">Mito ou verdade</option><option value="checklist">Checklist</option></select></div><div className="mt-5 max-h-[760px] space-y-3 overflow-y-auto">{filtered.map((post) => <div key={post.id} className="rounded-xl bg-slate-50 p-4"><button onClick={() => edit(post)} className="flex w-full items-center justify-between text-left"><div><p className="font-black">{post.title}</p><p className="mt-1 text-xs font-bold text-slate-400">{post.category ?? "legado"} · {post.editorialFormat ?? "card"} · {post.status}</p></div><Edit3 className="h-4 w-4 text-blue-600" /></button><button onClick={() => edit(post, true)} className="mt-3 inline-flex items-center gap-2 text-[10px] font-black uppercase text-blue-700"><CopyPlus className="h-4 w-4" />Duplicar como rascunho</button></div>)}</div></article>
  </section>;
};
